<?php 
	if (empty($_GET)) {
		# code...
		include "Konten/Dashboard.php";
	} elseif ($_GET['p']=="Home") {
		# code...
		include "Konten/Dashboard.php";
	} elseif ($_GET['p']=="Barang") {
		# code...
		include "Konten/Barang.php";
	} elseif ($_GET['p']=="Suplier") {
		# code...
		include "Konten/Suplier.php";
	} elseif ($_GET['p']=="Pengguna") {
		# code...
		include "Konten/Pengguna.php";
	} elseif ($_GET['p']=="Peminjaman") {
		# code...
		include "Konten/Peminjaman.php";
	} elseif ($_GET['p']=="Stok") {
		# code...
		include "Konten/Stok.php";
	} elseif ($_GET['p']=="Laporan") {
		# code...
		include "Konten/Laporan.php";
	} elseif ($_GET['p']=="Backup") {
		# code...
		include "Konten/Backup.php";
	} elseif ($_GET['p']=="Pengadaan") {
		# code...
		include "Konten/Pengadaan.php";
	} elseif ($_GET['p']=="tambahbarang") {
		# code...
		include "Konten/tambahbarang.php";
	} elseif ($_GET['p']=="tambahsuplier") {
		# code...
		include "Konten/tambahsuplier.php";
	} elseif ($_GET['p']=="tambahuser") {
		# code...
		include "Konten/tambahuser.php";
	} elseif ($_GET['p']=="editbarang") {
		# code...
		include "Konten/editbarang.php";
	} elseif ($_GET['p']=="editsuplier") {
		# code...
		include "Konten/editsuplier.php";
	} elseif ($_GET['p']=="editpengguna") {
		# code...
		include "Konten/editpengguna.php";
	} elseif ($_GET['p']=="editpengguna") {
		# code...
		include "Konten/editpengguna.php";
	} elseif ($_GET['p']=="tambahpengadaan") {
		# code...
		include "Konten/tambahpengadaan.php";
	} elseif ($_GET['p']=="tambahpengadaan") {
		# code...
		include "Konten/tambahpengadaan.php";
	} elseif ($_GET['p']=="editpengadaan") {
		# code...
		include "Konten/editpengadaan.php";
	} elseif ($_GET['p']=="tambahstok") {
		# code...
		include "Konten/tambahstok.php";
	} elseif ($_GET['p']=="editstok") {
		# code...
		include "Konten/editstok.php";
	} elseif ($_GET['p']=="tambahpinjaman") {
		# code...
		include "Konten/tambahpinjaman.php";
	} elseif ($_GET['p']=="editpinjaman") {
		# code...
		include "Konten/editpinjaman.php";
	} elseif ($_GET['p']=="editstok") {
		# code...
		include "Konten/editstok.php";
	} elseif ($_GET['p']=="Pengembalian") {
		# code...
		include "Konten/Pengembalian.php";
	} elseif ($_GET['p']=="barangkeluar") {
		# code...
		include "Konten/barangkeluar.php";
	} elseif ($_GET['p']=="tambahbarangkeluar") {
		# code...
		include "Konten/tambahbarangkeluar.php";
	} elseif ($_GET['p']=="ubahbarangkeluar") {
		# code...
		include "Konten/ubahbarangkeluar.php";
	} elseif ($_GET['p']=="levelpengguna") {
		# code...
		include "Konten/levelpengguna.php";
	} elseif ($_GET['p']=="tambahlevelpengguna") {
		# code...
		include "Konten/tambahlevelpengguna.php";
	} elseif ($_GET['p']=="editlevelpengguna") {
		# code...
		include "Konten/editlevelpengguna.php";
	} 
 ?>